# Generated by Django 5.2.7 on 2025-10-30 03:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_at',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_at',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.CharField(max_length=120),
        ),
    ]
