# Generated by Django 5.2.7 on 2025-10-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_event_price_cents_payment_ticket_calendarentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
