# Generated by assistant - add status and checked_in_at to Ticket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0005_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CHECKED_IN', 'Checked In'), ('NO_SHOW', 'No Show'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
