# Generated by Django 5.2.7 on 2025-11-07 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0007_add_event_organizer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Note: In some environments these legacy Ticket columns never existed.
        # Removing them conditionally is tricky on SQLite, so we simply skip the
        # removal here to avoid OperationalError: no such column. The current
        # Ticket model no longer references these fields, so the state remains consistent.
        migrations.AddField(
            model_name='event',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
