# Generated by Django 5.2.7 on 2025-11-06 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0007_add_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_tickets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event_management.venue'),
        ),
    ]
