# Generated by Django 5.2.7 on 2025-11-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0008_remove_ticket_checked_in_at_remove_ticket_status_and_more'),
    ]

    # This migration is intentionally a no-op.
    # The previous attempt to remove legacy Ticket fields caused failures on SQLite
    # when those columns were never present. Ticket model no longer references
    # these fields, so we keep the DB state as-is.
    operations = []
