# Generated by Django 5.2.7 on 2025-11-07 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0009_remove_ticket_checked_in_at_remove_ticket_status'),
    ]

    # Convert to a state-only migration to align historical state with the current models
    # without attempting to drop non-existent columns in SQLite.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='ticket',
                    name='checked_in_at',
                ),
                migrations.RemoveField(
                    model_name='ticket',
                    name='status',
                ),
            ],
        ),
    ]
