# Generated by Django 5.2.8 on 2025-11-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0012_ticket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
