# Generated by Django 5.2.7 on 2025-11-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_user_approval_requested_at_user_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved_organizer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_organizer',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='active', help_text='Used for organizer approval and general account state.', max_length=10),
        ),
    ]
