"""
Django settings for collegeEventsWeb project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file if present
env_path = os.path.join(Path(__file__).resolve().parent.parent, '.env')
if os.path.exists(env_path):
    # Ensure the .env file is UTF-8 encoded. If it's not, try common encodings and rewrite as UTF-8.
    try:
        with open(env_path, 'r', encoding='utf-8') as f:
            _ = f.read()
    except UnicodeDecodeError:
        try:
            with open(env_path, 'r', encoding='utf-16') as f:
                content = f.read()
        except UnicodeDecodeError:
            # last resort: open as latin-1 to avoid crashes
            with open(env_path, 'r', encoding='latin-1') as f:
                content = f.read()
        # rewrite as UTF-8 without BOM
        with open(env_path, 'w', encoding='utf-8') as f:
            f.write(content)

# Finally load .env using python-dotenv
load_dotenv(env_path)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure the project package directory is on sys.path so imports like
# 'collegeEventsWeb.event_management' work regardless of execution context.
import sys
sys.path.insert(0, str(BASE_DIR))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c*k3a$-m(g**d_d=a7io$peq5!p_s%5=++i_*i*w69ff722dgq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',

    # Local apps
    'event_management',
    'user_accounts',
    'ticket_services',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # Dev middleware: copy access_token cookie into Authorization header and
    # perform lightweight role checks for protected paths. Keeps JWT auth
    # working when the frontend uses httponly cookies in dev.
    'user_accounts.middleware.RoleAuthorizationMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Dev middleware: copy access_token cookie into Authorization header and
    # perform lightweight role checks for protected paths. Keeps JWT auth
    # working when the frontend uses httponly cookies in dev. Placed after
    # AuthenticationMiddleware so it can override request.user with the
    # JWT-authenticated user (otherwise Django's AuthenticationMiddleware
    # would later replace it with AnonymousUser).
    'user_accounts.middleware.RoleAuthorizationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'collegeEventsWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'collegeEventsWeb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Use environment variables for DB config (see .env.example)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'campus_events_db'),
        'USER': os.environ.get('POSTGRES_USER', 'campus_user'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

# Allow switching to SQLite for local development by setting USE_SQLITE=1 (default)
USE_SQLITE = os.environ.get('USE_SQLITE', '1')
if USE_SQLITE == '1' or USE_SQLITE.lower() in ('true', 'yes'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
]

CORS_ALLOW_CREDENTIALS = True

# Allow the front-end dev server origins for Django's CSRF origin check
# (Django requires explicit origins including scheme).
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
]

# Use the custom user model
AUTH_USER_MODEL = 'user_accounts.User'
