# Generated by Django 5.2.7 on 2025-10-25 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('qr_code', models.CharField(blank=True, max_length=255, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
