# Generated by Django 5.2.7 on 2025-10-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_services', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
