# Generated by Django 5.2.7 on 2025-11-01 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_rename_start_at_event_start_time_remove_event_end_at_and_more'),
        ('ticket_services', '0005_alter_ticket_created_at_alter_ticket_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='event_management.event'),
        ),
    ]
